# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-app
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.7'
  pod 'SDWebImage/WebP'
  pod 'Swifter', :git => 'https://github.com/mattdonnelly/Swifter.git'
  pod 'Default'
end

