#!/usr/bin/env bash

docker-compose build
docker-compose run --rm rails bundle install
docker-compose run --rm rails bundle exec spring binstub --all
docker-compose run --rm rails rails db:create
docker-compose run --rm rails rails db:migrate
docker-compose run --rm rails rails db:seed
